node_exporter_enabled: true
node_exporter_version: "1.1.2"
node_exporter_checksum: "8c1f6a317457a658e0ae68ad710f6b4098db2cad10204649b51e3c043aa3e70d"

process_exporter_enabled: true
process_exporter_version: "0.7.5"
process_exporter_checksum: "27f133596205654a67b4a3e3af11db640f7d4609a457f48c155901835bd349c6"
