- name: Update and upgrade the machine
  apt:
    upgrade: dist
    update_cache: true

- name: Install nvstat
  apt:
    name: vnstat
    state: present
    update_cache: yes

- name: firewall setup
  import_tasks: firewall.yml

- name: journald config
  import_tasks: journald.yml

- name: user and group
  import_tasks: user.yml

- name: Nginx setup
  import_tasks: nginx.yml

- name: service setup
  import_tasks: service.yml
